### PR TITLE
CI: Test build with latest dependencies

### PR DESCRIPTION
**Pull request by snowman2**

### CODE REVIEW

**Comment by djhoese** [comment]
FYI We borrowed from the dask/xarray crew and install unstable numpy too:

https://github.com/pytroll/satpy/blob/5504ea48a77969ec0df1ccdfdb51b73aa8b575c0/.github/workflows/ci.yaml#L97-L112

```
          python -m pip install \
          -f https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com \
          --no-deps --pre --upgrade \
          matplotlib \
          numpy \
          pandas \
          scipy; \
          python -m pip install \
          --no-deps --upgrade \
          git+https://github.com/dask/dask \
          git+https://github.com/dask/distributed \
          git+https://github.com/zarr-developers/zarr \
          git+https://github.com/Unidata/cftime \
          git+https://github.com/mapbox/rasterio \
          git+https://github.com/pydata/bottleneck \
          git+https://github.com/pydata/xarray;
```

**Comment by snowman2** [comment]
@djhoese thanks for the reference. Unfortunately, I think it is outdated [ref](https://github.com/pyproj4/pyproj-wheels/issues/27#issuecomment-669839099).

> Most people have moved to Anaconda.org instead now - there's a slightly complicated example in https://github.com/MacPython/pandas-wheels/blob/master/azure/posix.yml - see the end of the file.

**Comment by snowman2** [comment]
New path? `https://pypi.anaconda.org/scipy-wheels-nightly/simple`

**Comment by snowman2** [comment]
```
          python -m pip install \
            --extra-index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple/ \
            --trusted-host pypi.anaconda.org
            --no-deps --pre --upgrade \
            numpy \
            pandas \
            scipy;
```

**Comment by djhoese** [comment]
Trying to apply the same URL to the Satpy builds shows a lot of warnings about version inconsistencies and pip not wanting to use the packages.

**Comment by djhoese** [comment]
```
 Collecting scipy
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B5e9eb01/scipy-1.7.0.dev0%2B20210110040759_5e9eb01-cp38-cp38-manylinux1_x86_64.whl (27.3 MB)
WARNING: Discarding https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B5e9eb01/scipy-1.7.0.dev0%2B20210110040759_5e9eb01-cp38-cp38-manylinux1_x86_64.whl (from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/). Requested scipy from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B5e9eb01/scipy-1.7.0.dev0%2B20210110040759_5e9eb01-cp38-cp38-manylinux1_x86_64.whl has inconsistent version: filename has '1.7.0.dev0+20210110040759.5e9eb01', but metadata has '1.7.0.dev0+5e9eb01'
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B9b9f2e8/scipy-1.7.0.dev0%2B20210103040256_9b9f2e8-cp38-cp38-manylinux1_x86_64.whl (27.3 MB)
WARNING: Discarding https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B9b9f2e8/scipy-1.7.0.dev0%2B20210103040256_9b9f2e8-cp38-cp38-manylinux1_x86_64.whl (from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/). Requested scipy from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B9b9f2e8/scipy-1.7.0.dev0%2B20210103040256_9b9f2e8-cp38-cp38-manylinux1_x86_64.whl has inconsistent version: filename has '1.7.0.dev0+20210103040256.9b9f2e8', but metadata has '1.7.0.dev0+9b9f2e8'
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2Bb21b303/scipy-1.7.0.dev0%2B20201227035541_b21b303-cp38-cp38-manylinux1_x86_64.whl (27.2 MB)
WARNING: Discarding https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2Bb21b303/scipy-1.7.0.dev0%2B20201227035541_b21b303-cp38-cp38-manylinux1_x86_64.whl (from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/). Requested scipy from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2Bb21b303/scipy-1.7.0.dev0%2B20201227035541_b21b303-cp38-cp38-manylinux1_x86_64.whl has inconsistent version: filename has '1.7.0.dev0+20201227035541.b21b303', but metadata has '1.7.0.dev0+b21b303'
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B3cc6834/scipy-1.7.0.dev0%2B20201220035335_3cc6834-cp38-cp38-manylinux1_x86_64.whl (27.2 MB)
WARNING: Discarding https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B3cc6834/scipy-1.7.0.dev0%2B20201220035335_3cc6834-cp38-cp38-manylinux1_x86_64.whl (from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/). Requested scipy from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B3cc6834/scipy-1.7.0.dev0%2B20201220035335_3cc6834-cp38-cp38-manylinux1_x86_64.whl has inconsistent version: filename has '1.7.0.dev0+20201220035335.3cc6834', but metadata has '1.7.0.dev0+3cc6834'
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B6148b7c/scipy-1.7.0.dev0%2B20201213035410_6148b7c-cp38-cp38-manylinux1_x86_64.whl (27.2 MB)
WARNING: Discarding https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B6148b7c/scipy-1.7.0.dev0%2B20201213035410_6148b7c-cp38-cp38-manylinux1_x86_64.whl (from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/). Requested scipy from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.7.0.dev0%2B6148b7c/scipy-1.7.0.dev0%2B20201213035410_6148b7c-cp38-cp38-manylinux1_x86_64.whl has inconsistent version: filename has '1.7.0.dev0+20201213035410.6148b7c', but metadata has '1.7.0.dev0+6148b7c'
  Downloading scipy-1.6.1-cp38-cp38-manylinux1_x86_64.whl (27.3 MB)
```

**Comment by snowman2** [comment]
Maybe `--extra-index-url` should be `--index-url`

**Comment by snowman2** [comment]
> Trying to apply the same URL to the Satpy builds shows a lot of warnings about version inconsistencies and pip not wanting to use the packages.

Maybe something to raise upstream?

**Comment by djhoese** [comment]
But who/what/where is upstream?

**Comment by snowman2** [comment]
> But who/what/where is upstream?
- https://github.com/MacPython/pandas-wheels
- https://github.com/MacPython/numpy-wheels
- https://github.com/MacPython/scipy-wheels

**Comment by snowman2** [comment]
Already catching failures #260

**Review by justingruca — APPROVED** [review]

**Pull request merged**
