### PR TITLE
DOC: add example into write_crs

### LINKED ISSUE #262: add example of write_crs
There is an example of [`write_crs`](https://github.com/corteva/rioxarray/blob/master/rioxarray/rioxarray.py#L289) here: https://gis.stackexchange.com/questions/354782/how-to-mask-netcdf-time-series-data-from-a-shapefile-in-python/354798#354798

It could be added as as example to the doc string

### PR DESCRIPTION
**Pull request by raybellwaves**
- [x] Closes #262

### CODE REVIEW

**Comment by snowman2** [comment]
Thanks for this :+1:

Mind modifying the example to demonstrate two options?

To write the CRS of the current `xarray` object:
```python
raster.rio.write_crs(crs, inplace=True)
```
To write the CRS on a copy:
```python
raster = raster.rio.write_crs(crs)
```

**Comment by snowman2** [comment]
Looks like linting issues. The simplest fix is to setup pre-commit. See https://github.com/corteva/rioxarray/blob/master/CONTRIBUTING.rst#get-started

**Review by justingruca — APPROVED** [review]

**Comment by snowman2** [comment]
@raybellwaves this looks good. Did you want to squash your commits or do you mind if I squash and merge?

**Comment by raybellwaves** [comment]
> @raybellwaves this looks good. Did you want to squash your commits or do you mind if I squash and merge?

go for it

**Comment by snowman2** [comment]
Thanks @raybellwaves :+1:

**Pull request merged**
